spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path==/api/users/**
server:
  port: 8080

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/